name: beike_aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.7
homepage: https://github.com/LianjiaTech/Beike_AspectD

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:

  args: any
  path: any
  yaml: any

dependency_overrides:

  package_config: 1.9.3

  meta:
    path: pkg/meta

  frontend_server:
      path: pkg/frontend_server

  _fe_analyzer_shared:
      path: pkg/_fe_analyzer_shared

  vm:
      path: pkg/vm

  kernel:
      path: pkg/kernel
